added a missing items to the dashboards API.
mackerelio/mackerel-client-go pull request #120
Opened 2021-02-22 01:56 UTC by tukaelu

Added a missing items to Widget.

- FractionSize
- Suffix
- RoleFullName

https://mackerel.io/ja/api-docs/entry/dashboards#widget

2021-02-22 06:24 UTC, susisu requested changes

2021-02-23 08:51 UTC, susisu commented on dashboards.go
> +	FractionSize int64  `json:"fractionSize,omitempty"`
hmm... This is not as simple as I thought, and my comment above will not solve the problem.

Empty `fractionSize` should be treated as "empty", not zero, when both reading and writing JSON, so it is not expressible by just `int64`.
Maybe we can use `*int64` here?

2021-03-02 07:13 UTC, tukaelu commented on dashboards.go
> +	FractionSize int64  `json:"fractionSize,omitempty"`
Thank you for your review!

Fixed by changing fractionSize to * int64.
Please review again.

2021-03-03 01:30 UTC, susisu approved these changes
LGTM

2021-03-04 03:48 UTC, merged